In [140]:
import torch

In [141]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [142]:
print("number of elements in x: ", x.numel())
print("shape of x: ", x.shape)

number of elements in x:  12
shape of x:  torch.Size([12])


In [143]:
x.reshape(-1, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [144]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [145]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [146]:
torch.randn(3, 4)

tensor([[-0.1670,  0.2924,  0.2179,  0.5967],
        [-0.9911, -1.8123,  1.6000, -0.0795],
        [ 0.2857, -1.0116,  0.2306, -0.9570]])

## Indexing and Slicing

In [147]:
x[-1], x[1:3]

(tensor(11.), tensor([1., 2.]))

In [148]:
x[1] = 17

## Operations

In [149]:
torch.exp(x)

tensor([1.0000e+00, 2.4155e+07, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [150]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [151]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

We can also concatenate multiple tensors

In [152]:
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

Sometimes, we want to construct a binary tensor via logical statements. Take X == Y as an example

In [153]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summing all the elements in the tensor yields a tensor with only one element.

In [154]:
X.sum()

tensor(66.)

#### Broadcasting
By now, you know how to perform elementwise binary operations on two tensors of the same shape. Under certain conditions, even when shapes differ, we can still perform elementwise binary operations by invoking the broadcasting mechanism

In [ ]:
**Test**: 
- One of the dimensions is one


In [155]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(1, 3).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[1, 2]]))

Since ``a`` and ``b`` are `3 x 1` and `1 x 2`
matrices, respectively, their shapes do not match up. Broadcasting
produces a larger `3 x 2` matrix by replicating matrix ``a``
along the columns and matrix ``b`` along the rows before adding them
elementwise.

In [156]:
a + b, a - b

(tensor([[1, 2],
         [2, 3],
         [3, 4]]),
 tensor([[-1, -2],
         [ 0, -1],
         [ 1,  0]]))

#### Saving Memory
Running operations can cause new memory to be allocated to host results. For example, if we write Y = X + Y, we dereference the tensor that Y used to point to and instead point Y at the newly allocated memory.

In [157]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Fortunately, performing in-place operations is easy. We can assign the result of an operation to a previously allocated array Y by using slice notation `Y[:] = <expression>` as well as `Y += Z` 

In [158]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2360487565232
id(Z): 2360487565232


#### Conversion to Other Python Objects

Converting to a NumPy tensor (ndarray), or vice versa

In [159]:
A = X.numpy()
type(A)

numpy.ndarray

In [160]:
B = torch.from_numpy(A)
type(B)

torch.Tensor

To convert a size-1 tensor to a Python scalar

In [161]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)